Finalize package optimization

diff --git a/serverless/csc b/serverless/csc
--- a/serverless/csc
+++ b/serverless/csc
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
 
 # init
-readonly envFile='./../.env'
+envFile=${envFile:='./../.env'}
+binServerless=${binServerless:='sls'}
 
 # Usage
 usage () {
     echo ""
-    echo "  usage: cscraper.sh [--deploy] [--inv] [--invl]"
+    echo "  usage: . csc [--deploy] [--inv] [--invl]"
     echo ""
     exit 1
 }
@@ -18,8 +19,7 @@ usage () {
 if [ -f "${envFile}" ]; then
     source "${envFile}"
 else
-    echo "No '.env' file. Abort."
-    exit 1
+    echo "WARNING : No '.env' file."
 fi
 
 # Cmd handler
@@ -41,6 +41,10 @@ while [ ! -z $1 ]; do
     shift
 done
 
+function checkVar () {
+    [[ -z "$1" ]] && echo "ERROR : Missing environment variable : '$2'." && exit 1
+}
+
 function deploy() {
     ${binServerless} deploy
 }
@@ -56,6 +60,29 @@ function invoke() {
     [ -z $1 ] && local arg=''
     serverless invoke ${arg} -f cscraper
 }
+
+function getCloudFrontDomain() {
+    ${binServerless} domains | grep WebAppCloudFrontDistributionOutput | awk -F':' '{print $3}'
+}
+
+function getCloudFrontIP() {
+    getCloudFrontDomain |
+}
+
+#
+# Checks
+#
+
+checkVar "${S3_DNS}" "S3_DNS"
+checkVar "${ES_ENDPOINT_DEV}" "ES_ENDPOINT_DEV"
+checkVar "${ES_ALLOW_IP}" "ES_ALLOW_IP"
+checkVar "${AWS_REGION}" "AWS_REGION"
+checkVar "${AWS_USER}" "AWS_USER"
+checkVar "${AWS_ACCESS_KEY_ID}" "AWS_ACCESS_KEY_ID"
+checkVar "${AWS_SECRET_ACCESS_KEY}" "AWS_SECRET_ACCESS_KEY"
+checkVar "${CF_SSL_ARN}" "CF_SSL_ARN"
+checkVar "${APP_RSS_FEEDS}" "APP_RSS_FEEDS"
+checkVar "${APP_TITLE_REGEXP}" "APP_TITLE_REGEXP"
 
 #
 # Business logic here
